Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.box_check_update = false

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y curl
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server \
    --tls-san ${SERVER_IP} --write-kubeconfig-mode 644" sh -
  SHELL

  config.vm.define "vhappenhS" do |vhappenhS|
    vhappenhS.vm.hostname = "vhappenS"
    vhappenhS.vm.network "private_network", ip: '192.168.56.110'

    vhappenhS.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"  
      vb.cpus = 2        
    end
  end
end