# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.box_check_update = false

  config.vm.synced_folder "./data", "/vagrant_data"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y curl
  SHELL

  config.vm.define "vhappenhS" do |vhappenhS|
    vhappenhS.vm.hostname = "vhappenS"
    vhappenhS.vm.network "private_network", ip: '192.168.56.110'
    vhappenhS.vm.provision "shell", path: "./install-server.sh" 

    vhappenhS.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"  
      vb.cpus = 2        
    end
  end
  config.vm.define "vhappenhSW" do |vhappenhSW|
    vhappenhSW.vm.hostname = "vhappenSW"
    vhappenhSW.vm.network "private_network", ip: '192.168.56.111'
    vhappenhSW.vm.provision "shell", path: "./install-agent.sh" 

    vhappenhSW.vm.provider "virtualbox" do |vb|
      vb.memory = "512"  
      vb.cpus = 1    
    end
  end
end
