Vagrant.configure("2") do |config|
    config.vm.box       = "debian/bookworm64"
    config.vm.hostname  = "lyeh"

    config.vm.provider "virtualbox" do |vb|
        vb.name     = "S"
        vb.memory   = 512
        vb.cpus     = 1
    end
end

