apiVersion: v1
kind: ConfigMap
metadata:
  name: app2-html
  namespace: kube-system
data:
  index.html: |
    <!doctype html>
    <html lang="en">
    <head><meta charset="utf-8"><title>app2</title></head>
    </html>
