# bonus/manifests/argocd/application-dev.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bonus-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://localhost:8081/root/my-repo.git
    targetRevision: main
    path: bonus/manifests/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
