apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: p3-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/42-CC-RNCP/Inception-of-Things.git
    targetRevision: lea/p3
    path: p3/manifests/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
